# version: '3'
# services:
#   web:
#     build:
#       context: .
#       dockerfile: Dockerfile
#       tags:
#         - myapp
#     ports:
#       - "80:80"
version: "3"
services:
  app:
    image: ${env.REPO_NAME}:${env.TAG}
    ports:
      - "80:80"